"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useSupabase } from "@/components/supabase-provider";
import { Button } from "@/components/ui/button";
const tables = [{ table: "skills", name: "Skills", path: "skills" }, { table: "projects", name: "Projects", path: "projects" }, { table: "certifications", name: "Certifications", path: "certifications" }, { table: "experiences", name: "Experience", path: "experience" }, { table: "achievements", name: "Achievements", path: "achievements" }];
export default function DashboardOverview() {
  const supabase = useSupabase(); const [counts, setCounts] = useState<Record<string, number>>({}); const [error, setError] = useState("");
  useEffect(() => { if (!supabase) return; let cancelled = false; void Promise.all(tables.map(async ({ table }) => { const { count, error } = await supabase.from(table).select("id", { count: "exact", head: true }); if (error) throw error; return [table, count || 0] as const; })).then(rows => { if (!cancelled) setCounts(Object.fromEntries(rows)); }).catch(() => { if (!cancelled) setError("Content could not be loaded. Check the Supabase connection and run the database setup SQL."); }); return () => { cancelled = true; }; }, [supabase]);
  return <><div className="admin-page-heading"><div><h1>Dashboard</h1><p>Manage the content behind your portfolio.</p></div></div>{error && <p role="alert" className="admin-error">{error}</p>}<div className="admin-stats">{tables.map(({ table, name, path }) => <Link className="admin-stat" href={`/admin/dashboard/${path}/`} key={table}><span>{name}</span><strong>{counts[table] ?? "—"}</strong><p>{["skills", "projects"].includes(table) ? "Manage content" : "Prepared section"}</p></Link>)}</div><div className="admin-information"><h2>Your public portfolio stays public</h2><p>Skills and published projects load from Supabase on each visit. Save changes here, then reload the portfolio to see them. Draft and archived projects stay out of the public portfolio.</p><div className="flex flex-wrap gap-3 mt-5"><Button asChild><Link href="/admin/dashboard/skills/">Manage skills</Link></Button><Button asChild variant="outline"><Link href="/admin/dashboard/projects/">Manage projects</Link></Button></div></div><div className="admin-information"><h2>Ready for your next update</h2><p>Certifications, Experience, and Achievements have database tables, security policies, and dashboard sections. Their editing screens can be added later; the public sections already load these saved records from Supabase in the existing design.</p></div></>;
}
