"use client";
import { useEffect, useState } from "react";
import { useSupabase } from "@/components/supabase-provider";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
const definitions = { certifications: { title: "Certifications", table: "certifications" }, experience: { title: "Experience", table: "experiences" }, achievements: { title: "Achievements", table: "achievements" } };
export default function PreparedSection({ section }: { section: keyof typeof definitions }) {
  const definition = definitions[section]; const supabase = useSupabase(); const [rows, setRows] = useState<{ id: string; title: string; display_order: number }[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { if (!supabase) return; let cancelled = false; void supabase.from(definition.table).select("id,title,display_order").order("display_order").order("created_at").then(({ data, error }) => { if (cancelled) return; if (error) setError("This section could not be loaded. Check the Supabase setup."); else { setRows(data || []); setError(""); } setLoading(false); }); return () => { cancelled = true; }; }, [supabase, definition.table]);
  return <><div className="admin-page-heading"><div><h1>{definition.title}</h1><p>Prepared for future content management.</p></div></div><div className="admin-notice"><strong>Editing screen coming in a later update</strong><p>This page previews saved records. The public portfolio loads these records from Supabase; you can update them in the Supabase dashboard until the editing screen is added.</p></div>{error && <p className="admin-error" role="alert">{error}</p>}<div className="admin-table-wrap"><Table><TableHeader><TableRow><TableHead>Title</TableHead><TableHead>Display order</TableHead></TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.id}><TableCell>{row.title}</TableCell><TableCell>{row.display_order}</TableCell></TableRow>)}{rows.length === 0 && <TableRow><TableCell colSpan={2}>{loading ? "Loading…" : "No records yet."}</TableCell></TableRow>}</TableBody></Table></div></>;
}
